package cn.freeteam.dao;

import cn.freeteam.model.FreecmsDemo;
import cn.freeteam.model.FreecmsDemoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreecmsDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int countByExample(FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int deleteByExample(FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int insert(FreecmsDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int insertSelective(FreecmsDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    List<FreecmsDemo> selectByExampleWithBLOBs(FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    List<FreecmsDemo> selectByExample(FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    FreecmsDemo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") FreecmsDemo record, @Param("example") FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") FreecmsDemo record, @Param("example") FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int updateByExample(@Param("record") FreecmsDemo record, @Param("example") FreecmsDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int updateByPrimaryKeySelective(FreecmsDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(FreecmsDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_demo
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    int updateByPrimaryKey(FreecmsDemo record);
}