package cn.freeteam.model;

public class FreecmsTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.id
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.name
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.id
     *
     * @return the value of freecms_test.id
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.id
     *
     * @param id the value for freecms_test.id
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.name
     *
     * @return the value of freecms_test.name
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.name
     *
     * @param name the value for freecms_test.name
     *
     * @mbggenerated Tue Feb 25 09:11:47 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}